---
- hosts: web
  remote_user: root
  tasks:
    - name: create joe user
      user: name=joe
            system=yes
            groups="sudo"
            password=$6$rounds=100000$YWoCUqN/MYPzTS5c$oUCt/Ko/eVNyIeKksHTNTTlurS3Wz0Q8Zt0mCMcPVOxtvpvPWe6Q5s.II3cvjZnsJ6cVyoWMTVg3WxvchhvKy.
    - name: copy root ssh key
      command: cp /root/.ssh/authorized_keys /home/joe/.ssh/authorized_keys
               creates=/home/joe/.ssh/authorized_keys
    - name: install nginx
      apt: name=nginx update_cache=yes
