---
- hosts: all
  remote_user: root
  tasks:
    - include: tasks/weechat.yml
    - include: tasks/joe.yml
    - include: tasks/ssh.yml
    - include: tasks/docker.yml
    - include: tasks/nginx.yml
    - include: tasks/joe.xoxomoon.com.yml
    - include: tasks/xoxomoon.com.yml
    - include: tasks/servicerecordbook.com.yml
    - include: tasks/beverlymoon.com.yml
  handlers:
    - include: handlers/nginx.yml
