---
- hosts: all
  remote_user: "{{ user }}"
  roles:
    - angstwad.docker_ubuntu
    - bobbyrenwick.pip
  tasks:
    - include: tasks/joe.yml
      when: not vagrant
    - include: tasks/ssh.yml
      when: not vagrant
    - include: tasks/nginx.yml
      sudo: true
    - include: tasks/git.yml
      sudo: true
    - include: tasks/joe.xoxomoon.com.yml
    - include: tasks/xoxomoon.com.yml
    - include: tasks/servicerecordbook.com.yml
    - include: tasks/beverlymoon.com.yml
  handlers:
    - include: handlers/nginx.yml
