---
- hosts: all
  remote_user: root
  tasks:
    - name: create joe user
      user: name=joe
            system=yes
            groups="sudo"
            password=$6$rounds=100000$YWoCUqN/MYPzTS5c$oUCt/Ko/eVNyIeKksHTNTTlurS3Wz0Q8Zt0mCMcPVOxtvpvPWe6Q5s.II3cvjZnsJ6cVyoWMTVg3WxvchhvKy.
    - name: copy root ssh key
      command: cp -r /root/.ssh /home/joe/.ssh
               creates=/home/joe/.ssh/authorized_keys
    - name: install nginx
      apt: name=nginx
           update_cache=yes
      notify:
        - start nginx
    - name: get nginx.conf
      template: src=./nginx.conf
                dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
    - name: ensure nginx is running
      service: name=nginx
               state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
