---
- name: docker-py hack
  pip: name=docker-py state=absent

- name: docker-py hack2
  pip: name=docker-py version=1.2.3 state=present

- name: run preterition-db docker image
  docker:
    image: joebadmo/preterition-db
    name: db
    env: POSTGRES_PASSWORD=foo
    pull: "always"

- name: run preterition docker image
  docker:
    pull: "always"
    image: joebadmo/preterition
    links:
      - "db:db"
    ports: "3000:3000"
    pull: "always"
